name: test coverage codacy

on: ["push"]

jobs:
  Run-coverage-on-Ubuntu:
    name: Run coverage linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run codacy coverage reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKE }}
          coverage-reports: src.lcov

