name: test coverage codacy

on: ["push"]

jobs:
  Run-coverage-on-Ubuntu:
    name: Run coverage linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: send coverage
        working-directory: ${{ github.workspace }}
        run: bash ./get.sh report -t ${{ secrets.CODACY_PROJECT_TOKEN }}
  Run-coverage-on-macos:
    name: Run coverage macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: send coverage
        working-directory: ${{ github.workspace }}
        run: bash ./get.sh report -t ${{ secrets.CODACY_PROJECT_TOKEN }}
  Run-coverage-on-windows:
    name: Run coverage windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: send coverage
        working-directory: ${{ github.workspace }}
        run: bash ./get.sh report -t ${{ secrets.CODACY_PROJECT_TOKEN }}
